apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: rhoai-scikit-learn-template
  title: Machine Learning with Scikit Learn on RHOAI Template 
  description: Deploy a data science project with a regression exercise on RHOAI
  tags:
    - ml
    - workshop
    - python    
spec:
  owner: rhdeveloper-workshop-authors
  type: service

  parameters: 
    - title: Provide information for GitLab
      required:
        - gitlabGroup
      properties:
        gitlabGroup:
          title: GitLab Group
          type: string
          description: Your GitLab group
          default: development
          enum:
            - development
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
          default: RHOAI data science project with a scikit-learn regression exercise
    - title: Provide information about the new component
      required:
        - clusterId
        - namespace
      properties:
        clusterId:
          title: Cluster Id
          type: string
          description: Id of the cluster
          default: .apps.cluster-kpxpg.sandbox1408.opentlc.com
        namespace: 
          title: Namespace
          type: string
          description: Namespace
          default: my-dsp

  steps:
    - id: templateSource
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./source
        values:
          repoName: ${{parameters.namespace}}-rhoai-sklearn
          owner: ${{ user.entity.metadata.name }}
          clusterId: ${{parameters.clusterId}}
          namespace: ${{parameters.namespace}}
          componentId: ${{parameters.namespace}}-rhoai-sklearn-dsp

    - id: publishSource
      name: Publishing to Source Code Repository
      action: publish:gitlab
      input:
        allowedHosts:
          - gitlab.com
        sourcePath: ./source
        description: ${{parameters.description}}
        repoUrl: gitlab-gitlab${{parameters.clusterId}}?owner=${{parameters.gitlabGroup}}&repo=${{parameters.namespace}}-rhoai-sklearn
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public    

    - id: registerSource
      name: Registering the Source Code Component
      action: catalog:register
      input:
        repoContentsUrl: ${{steps.publishSource.output.repoContentsUrl}}
        catalogInfoPath: /catalog-info.yaml

    - id: templateGitOps
      name: Generating the deployment resources and artifacts
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          componentId: ${{parameters.namespace}}-rhoai-sklearn-dsp
          description: ${{parameters.description}}
          destination: https://gitlab-gitlab${{parameters.clusterId}}/${{parameters.gitlabGroup}}/${{parameters.namespace}}-rhoai-sklearn-gitops.git
          sourceRepository: https://gitlab-gitlab${{parameters.clusterId}}/${{parameters.gitlabGroup}}/${{parameters.namespace}}-rhoai-sklearn.git
          repository_name: ${{parameters.namespace}}-rhoai-sklearn
          defaultBranch: main
          cluster: ${{parameters.clusterId}}
          namespace: ${{parameters.namespace}}
        targetPath: ./tenant-gitops

    - id: publishGitOps
      name: Publishing to Deployment Resource Repository
      action: publish:gitlab
      input:
        allowedHosts:
          - gitlab.com
        repoUrl: gitlab-gitlab${{parameters.clusterId}}?owner=${{parameters.gitlabGroup}}&repo=${{parameters.namespace}}-rhoai-sklearn-gitops
        title: GitOps resources for ${{parameters.namespace}}-rhoai-sklearn-dsp
        description: GitOps resources for ${{parameters.namespace}}-rhoai-sklearn-dsp
        sourcePath: ./tenant-gitops
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public

    - id: createArgoResources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{parameters.namespace}}-rhoai-sklearn-dsp-bootstrap
        argoInstance: main
        namespace: janus-argocd 
        repoUrl: https://gitlab-gitlab${{parameters.clusterId}}/${{parameters.gitlabGroup}}/${{parameters.namespace}}-rhoai-sklearn-gitops.git
        path: 'argocd/'

  output:
    links:
      - title: Source Code Repository
        url: ${{steps.publishSource.output.remoteUrl}}
      - title: Pipeline status
        url: https://console-openshift-console${{parameters.clusterId}}/dev-pipelines/ns/${{parameters.namespace}}/
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{steps.registerSource.output.entityRef}}